[package]
name = "message_macro_derive"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
proc-macro = true


[dependencies]
syn = { version = "2.0", features = ["extra-traits", "parsing"] }
quote = "1.0"
