name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install cargo-deb
      run: cargo install cargo-deb
    - name: Create .deb file
      run: cargo deb -p twamp
    - name: Publish .deb to GitHub Packages
      uses: actions/upload-artifact@v2
      with:
        name: network-tools-deb
        path: target/debian/*.deb
